name: Deploy React App

on:
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Node.js and dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the version you need
          
      - name: Install dependencies
        run: npm install

      # 3. Build the React app
      - name: Build React App
        run: npm run build

      # 4. Deploy only changed files using lftp
      - name: Deploy to FTP Server
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          # Install lftp
          sudo apt-get update && sudo apt-get install -y lftp
          
          # Sync files to the remote server, uploading only modified files
          lftp -c "
          open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST;
          mirror -R -P 5 --verbose ./build $REMOTE_DIR;
          bye;
          "
